### ISSUE TITLE
[Feature]: HERD/TermSet Expansion Tracker

### ISSUE THREAD

**Issue by mavaylon1** [hdmf-dev/hdmf#966]
### What would you like to see added to HDMF?

This ticket is to be the central hub for all things HERD, TermSet and TermSetWrapper. This is due to multiple discussed changes and existing tickets that make it difficult to track progress and the order of development.

- [ ] Add back prior `add_ref_termset` functionality such that the user can provide a termset to `add_ref`. This would require renaming the current `add_ref_termset` as the name does not completely relate to method scope.
- [ ] TermSetWrapper with iterative write #930
- [ ] TermSetWrapper with DataIO #954
- [ ] TermSet compound data #938
- [ ] Where and how to cache the termset itself. #949
- [ ] HERD format on write
- [ ] `add_ref` needs to update how to handle the bulk creation of references. This would involve resolving keys and entities, rather than returning an error. #961 
- [ ] Create a demo that uses a DANDI set 

### What solution would you like?

Refer Above.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/hdmf-dev/hdmf/blob/dev/.github/CODE_OF_CONDUCT.md)
- [X] Have you checked the [Contributing](https://github.com/hdmf-dev/hdmf/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/hdmf-dev/hdmf/issues)?

**Comment by mavaylon1** [comment]
@oruebel I created this to help us keep track of the ideas we talked about and the ideas that are now coming up.
